services:
  promtail:
    image: grafana/promtail:latest
    container_name: cloudops-promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
    command:
      - -config.file=/etc/promtail/config.yml
    networks:
      - api_default

networks:
  api_default:
    external: true
